name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-custom-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: test crate
        run: |
          cd opt-einsum-path
          cargo test
